import { Router, type IRouter } from "express";
import healthRouter from "./health";
import userAuthRouter from "./userAuth";
import budgetLinesRouter from "./budget-lines";
import budgetLinesWithMonthlyRouter from "./budget-lines-with-monthly";
import monthlyPlansRouter from "./monthly-plans";
import monthlyActualsRouter from "./monthly-actuals";
import alertsRouter from "./alerts";
import alertsEngineRouter from "./alerts-engine";
import eventsRouter from "./events";
import dashboardRouter from "./dashboard";
import chartsRouter from "./charts";
import projectionsRouter from "./projections";
import importsRouter from "./imports";
import boardRouter from "./board";
import reforecastRouter from "./reforecast";
import auditLogsRouter from "./audit-logs";
import adminRouter from "./admin";
import seedRouter from "./seed";

const router: IRouter = Router();

router.use(healthRouter);
router.use(userAuthRouter);
router.use(dashboardRouter);
router.use(chartsRouter);
router.use(projectionsRouter);
router.use(budgetLinesWithMonthlyRouter);
router.use(budgetLinesRouter);
router.use(monthlyPlansRouter);
router.use(monthlyActualsRouter);
router.use(alertsRouter);
router.use(alertsEngineRouter);
router.use(eventsRouter);
router.use(importsRouter);
router.use(boardRouter);
router.use(reforecastRouter);
router.use(auditLogsRouter);
router.use(adminRouter);
router.use(seedRouter);

export default router;
